version: "3.4"

networks:
  test-network:
    driver: bridge
  
services:
  example:
    build: example/
    networks:
      - test-network

  micro:
    image: micro/micro
    command: server
    depends_on:
      - example
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    networks:
      - test-network
