version: "3.4"

networks:
  test-network:
    driver: bridge
  
services:
  example:
    build: example/

  etcd:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  micro:
    image: micro/micro:latest
    command: server
    depends_on:
      - example
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    environment:
      - MICRO_REGISTRY=etcd
      - MICRO_LOG_LEVEL=debug
      - MICRO_REGISTRY_ADDRESS=etcd:2379
      - MICRO_WEB_ADDRESS=0.0.0.0:8082
